
public enum ISOCountryTwoDigitCode {
    /* According to:  http://support.worldpay.com/support/kb/gg/corporate-gateway-guide/content/reference/usefultables.htm */

    AF ("AFGHANISTAN"),
    AX ("ALAND ISLANDS"),
    AL ("ALBANIA"),
    DZ ("ALGERIA"),
    AS ("AMERICAN SAMOA"),
    AD ("ANDORRA"),
    AO ("ANGOLA"),
    AI ("ANGUILLA"),
    AQ ("ANTARCTICA"),
    AG ("ANTIGUA AND BARBUDA"),
    AR ("ARGENTINA"),
    AM ("ARMENIA"),
    AW ("ARUBA"),
    AU ("AUSTRALIA"),
    AT ("AUSTRIA"),
    AZ ("AZERBAIJAN"),
    BS ("BAHAMAS"),
    BH ("BAHRAIN"),
    BD ("BANGLADESH"),
    BB ("BARBADOS"),
    BY ("BELARUS"),
    BE ("BELGIUM"),
    BZ ("BELIZE"),
    BJ ("BENIN"),
    BM ("BERMUDA"),
    BT ("BHUTAN"),
    BO ("BOLIVIA"),
    BQ ("BONAIRE, SINT EUSTATIUS AND SABA"),
    BA ("BOSNIA AND HERZEGOVINA"),
    BW ("BOTSWANA"),
    BV ("BOUVET ISLAND"),
    BR ("BRAZIL"),
    IO ("BRIT. IND. OCEAN TERRIT."),
    BN ("BRUNEI DARUSSALAM"),
    BG ("BULGARIA"),
    BF ("BURKINA FASO"),
    BI ("BURUNDI"),
    KH ("CAMBODIA"),
    CM ("CAMEROON"),
    CA ("CANADA"),
    CV ("CAPE VERDE"),
    KY ("CAYMAN ISLANDS"),
    CF ("CENTRAL AFRICAN REPUBLIC"),
    TD ("CHAD"),
    CL ("CHILE"),
    CN ("CHINA"),
    CX ("CHRISTMAS ISLAND"),
    CC ("COCOS (KEELING) ISLANDS"),
    CO ("COLOMBIA"),
    KM ("COMOROS"),
    CG ("CONGO"),
    CD ("CONGO, THE DEMOCRATIC REPUBLIC OF THE"),
    CK ("COOK ISLANDS"),
    CR ("COSTA RICA"),
    CI ("COTE D'IVOIRE"),
    HR ("CROATIA"),
    CU ("CUBA"),
    CW ("CURACAO"),
    CY ("CYPRUS"),
    CZ ("CZECH REPUBLIC"),
    DK ("DENMARK"),
    DJ ("DJIBOUTI"),
    DM ("DOMINICA"),
    DO ("DOMINICAN REPUBLIC"),
    TP ("EAST TIMOR"),
    EC ("ECUADOR"),
    EG ("EGYPT"),
    SV ("EL SALVADOR"),
    GQ ("EQUATORIAL GUINEA"),
    ER ("ERITREA"),
    EE ("ESTONIA"),
    ET ("ETHIOPIA"),
    FK ("FALKLAND ISLANDS"),
    FO ("FAROE ISLANDS"),
    FJ ("FIJI"),
    FI ("FINLAND"),
    FR ("FRANCE"),
    FX ("FRANCE, METROPOLITAN"),
    GF ("FRENCH GUIANA"),
    PF ("FRENCH POLYNESIA"),
    TF ("FRENCH SOUTHERN TERRIT."),
    GA ("GABON"),
    GM ("GAMBIA"),
    GE ("GEORGIA"),
    DE ("GERMANY"),
    GH ("GHANA"),
    GI ("GIBRALTAR"),
    GR ("GREECE"),
    GL ("GREENLAND"),
    GD ("GRENADA"),
    GP ("GUADELOUPE"),
    GU ("GUAM"),
    GT ("GUATEMALA"),
    GG ("GUERNSEY"),
    GN ("GUINEA"),
    GW ("GUINEA-BISSAU"),
    GY ("GUYANA"),
    HT ("HAITI"),
    HM ("HEARD & MC DONALD ISLS"),
    HN ("HONDURAS"),
    HK ("HONG KONG"),
    HU ("HUNGARY"),
    IS ("ICELAND"),
    IN ("INDIA"),
    ID ("INDONESIA"),
    IR ("IRAN"),
    IQ ("IRAQ"),
    IE ("IRELAND"),
    IM ("ISLE OF MAN"),
    IL ("ISRAEL"),
    IT ("ITALY"),
    JM ("JAMAICA"),
    JP ("JAPAN"),
    JE ("JERSEY"),
    JO ("JORDAN"),
    KZ ("KAZAKHSTAN"),
    KE ("KENYA"),
    KI ("KIRIBATI"),
    KS ("KOSOVO"),
    KW ("KUWAIT"),
    KG ("KYRGYZSTAN"),
    LA ("LAO PEOPLE'S REP."),
    LV ("LATVIA"),
    LB ("LEBANON"),
    LS ("LESOTHO"),
    LR ("LIBERIA"),
    LY ("LIBYAN ARAB JAMAHIRIYA"),
    LI ("LIECHTENSTEIN"),
    LT ("LITHUANIA"),
    LU ("LUXEMBOURG"),
    MO ("MACAU"),
    MK ("MACEDONIA"),
    MG ("MADAGASCAR"),
    MW ("MALAWI"),
    MY ("MALAYSIA"),
    MV ("MALDIVES"),
    ML ("MALI"),
    MT ("MALTA"),
    MH ("MARSHALL ISLANDS"),
    MQ ("MARTINIQUE"),
    MR ("MAURITANIA"),
    MU ("MAURITIUS"),
    YT ("MAYOTTE"),
    MX ("MEXICO"),
    FM ("MICRONESIA (FED. STATES)"),
    MD ("MOLDOVA, REPUBLIC OF"),
    MC ("MONACO"),
    MN ("MONGOLIA"),
    MS ("MONTSERRAT"),
    MA ("MOROCCO"),
    MZ ("MOZAMBIQUE"),
    MM ("MYANMAR"),
    NA ("NAMIBIA"),
    NR ("NAURU"),
    NP ("NEPAL"),
    NL ("NETHERLANDS"),
    NC ("NEW CALEDONIA"),
    NZ ("NEW ZEALAND"),
    NI ("NICARAGUA"),
    NE ("NIGER"),
    NG ("NIGERIA"),
    NU ("NIUE"),
    NF ("NORFOLK ISLAND"),
    MP ("NORTHERN MARIANA ISLANDS"),
    NO ("NORWAY"),
    OM ("OMAN"),
    PK ("PAKISTAN"),
    PW ("PALAU"),
    PS ("PALESTINIAN TERRITORY, OCCUPIED"),
    PA ("PANAMA"),
    PG ("PAPUA NEW GUINEA"),
    PY ("PARAGUAY"),
    KP ("PEOPLE'S REP. KOREA"),
    PE ("PERU"),
    PH ("PHILIPPINES"),
    PN ("PITCAIRN"),
    PL ("POLAND"),
    PT ("PORTUGAL"),
    PR ("PUERTO RICO"),
    QA ("QATAR"),
    KR ("REPUBLIC OF KOREA"),
    ME ("REPUBLIC OF MONTENEGRO"),
    RS ("REPUBLIC OF SERBIA"),
    RE ("REUNION"),
    RO ("ROMANIA"),
    RU ("RUSSIAN FEDERATION"),
    RW ("RWANDA"),
    GS ("S. GEORGIA & S. SANDWICH"),
    BL ("SAINT BARTHELEMY"),
    KN ("SAINT KITTS AND NEVIS"),
    LC ("SAINT LUCIA"),
    MF ("SAINT MARTIN (FRENCH)"),
    WS ("SAMOA"),
    SM ("SAN MARINO"),
    ST ("SAO TOME AND PRINCIPE"),
    SA ("SAUDI ARABIA"),
    SN ("SENEGAL"),
    CS ("SERBIA AND MONTENEGRO"),
    SC ("SEYCHELLES"),
    SL ("SIERRA LEONE"),
    SG ("SINGAPORE"),
    SX ("SINT MAARTEN (DUTCH)"),
    SK ("SLOVAKIA"),
    SI ("SLOVENIA"),
    SB ("SOLOMON ISLANDS"),
    SO ("SOMALIA"),
    ZA ("SOUTH AFRICA"),
    ES ("SPAIN"),
    LK ("SRI LANKA"),
    SH ("ST. HELENA"),
    PM ("ST. PIERRE AND MIQUELON"),
    VC ("ST. VINCENT & GRENADINES"),
    SD ("SUDAN"),
    SR ("SURINAME"),
    SJ ("SVALBARD AND JAN MAYEN"),
    SE ("SWEDEN"),
    CH ("SWITZERLAND"),
    SY ("SYRIAN ARAB REPUBLIC"),
    TW ("TAIWAN"),
    TJ ("TAJIKISTAN"),
    TZ ("TANZANIA"),
    TL ("TIMOR-LESTE"),
    TG ("TOGO"),
    TK ("TOKELAU"),
    TO ("TONGA"),
    TT ("TRINIDAD AND TOBAGO"),
    TN ("TUNISIA"),
    TR ("TURKEY"),
    TM ("TURKMENISTAN"),
    TC ("TURKS AND CAICOS ISLANDS"),
    TV ("TUVALU"),
    UG ("UGANDA"),
    UA ("UKRAINE"),
    AE ("UNITED ARAB EMIRATES"),
    GB ("UNITED KINGDOM"),
    US ("UNITED STATES"),
    UY ("URUGUAY"),
    UM ("US MINOR OUTL. ISLANDS"),
    UZ ("UZBEKISTAN"),
    VU ("VANUATU"),
    VA ("VATICAN CITY STATE"),
    VE ("VENEZUELA"),
    VN ("VIET NAM"),
    VG ("VIRGIN ISLANDS (BRITISH)"),
    VI ("VIRGIN ISLANDS (U.S.)"),
    WF ("WALLIS & FUTUNA ISLANDS"),
    EH ("WESTERN SAHARA"),
    YE ("YEMEN"),
    YU ("YUGOSLAVIA"),
    ZR ("ZAIRE"),
    ZM ("ZAMBIA"),
    ZW ("ZIMBABWE");

    private String countryCode;

    ISOCountryTwoDigitCode(String country) {
        this.countryCode = country;
    }

    public String getCountryCode() {
        return countryCode;
    }

    public static ISOCountryTwoDigitCode fromString(String text) {

        if (text != null) {
            for (ISOCountryTwoDigitCode isoCountryTwoDigitCode : ISOCountryTwoDigitCode.values()) {
                if (text.equalsIgnoreCase(isoCountryTwoDigitCode.getCountryCode()) || text.equalsIgnoreCase(isoCountryTwoDigitCode.name())) {
                    return isoCountryTwoDigitCode;
                }
            }
        }

        throw new IllegalArgumentException(String.format("Unknown enum type %s", text));
    }
}
